import type { AgendaExam } from '../types/agenda';

const prof1 = {
  id: 'prof-001',
  name: 'Dr. João Silva',
  email: 'joao.silva@odontaval.com',
  roles: [{ id: 2, name: 'PROFESSOR' as const }],
};

const prof2 = {
  id: 'prof-002',
  name: 'Dra. Mariana Costa',
  email: 'mariana.costa@odontaval.com',
  roles: [{ id: 2, name: 'PROFESSOR' as const }],
};

export const MOCK_AGENDA_EXAMS: AgendaExam[] = [
  {
    id: 1,
    title: 'Avaliação Clínica - Dentística',
    date: '2026-05-06',
    academicSemester: '2026.1',
    goals: 'Avaliar restauração composta classe II',
    serviceUnit: 'Box 01',
    procedurePerformed: 'Restauração composta',
    professorId: 'prof-001',
    specialismId: 1,
    specialism: { id: 1, name: 'Dentística', description: 'Estética e restauração dental' },
    professor: prof1,
    evaluationCount: 5,
    status: 'in_progress',
  },
  {
    id: 2,
    title: 'Avaliação Clínica - Endodontia',
    date: '2026-05-06',
    academicSemester: '2026.1',
    goals: 'Avaliar tratamento de canal radicular',
    serviceUnit: 'Box 03',
    procedurePerformed: 'Tratamento de canal',
    professorId: 'prof-002',
    specialismId: 3,
    specialism: { id: 3, name: 'Endodontia', description: 'Tratamento de canal' },
    professor: prof2,
    evaluationCount: 3,
    status: 'scheduled',
  },
  {
    id: 3,
    title: 'Avaliação Diagnóstica - Ortodontia',
    date: '2026-05-08',
    academicSemester: '2026.1',
    goals: 'Avaliação diagnóstica inicial',
    serviceUnit: 'Box 02',
    procedurePerformed: 'Diagnóstico ortodôntico',
    professorId: 'prof-001',
    specialismId: 2,
    specialism: { id: 2, name: 'Ortodontia', description: 'Correção de má oclusão' },
    professor: prof1,
    evaluationCount: 8,
    status: 'completed',
  },
  {
    id: 4,
    title: 'Avaliação Periodontal',
    date: '2026-05-12',
    academicSemester: '2026.1',
    goals: 'Avaliar saúde periodontal e higiene oral',
    serviceUnit: 'Box 04',
    procedurePerformed: 'Raspagem supra e subgengival',
    professorId: 'prof-002',
    specialismId: 4,
    specialism: { id: 4, name: 'Periodontia', description: 'Tratamento gengival' },
    professor: prof2,
    evaluationCount: 6,
    status: 'completed',
  },
  {
    id: 5,
    title: 'Cirurgia Oral Simulada',
    date: '2026-05-12',
    academicSemester: '2026.1',
    goals: 'Avaliar técnica cirúrgica de exodontia',
    serviceUnit: 'Centro Cirúrgico',
    procedurePerformed: 'Exodontia simples',
    professorId: 'prof-001',
    specialismId: 5,
    specialism: { id: 5, name: 'Cirurgia Oral', description: 'Procedimentos cirúrgicos' },
    professor: prof1,
    evaluationCount: 0,
    status: 'scheduled',
  },
  {
    id: 6,
    title: 'Avaliação de Prótese Dentária',
    date: '2026-05-15',
    academicSemester: '2026.1',
    goals: 'Avaliar moldagem e instalação de prótese total',
    serviceUnit: 'Laboratório de Prótese',
    procedurePerformed: 'Instalação de prótese total',
    professorId: 'prof-002',
    specialismId: 6,
    specialism: { id: 6, name: 'Prótese Dentária', description: 'Reabilitação oral' },
    professor: prof2,
    evaluationCount: 4,
    status: 'completed',
  },
  {
    id: 7,
    title: 'Avaliação Clínica - Dentística Avançada',
    date: '2026-05-19',
    academicSemester: '2026.1',
    goals: 'Restauração cerâmica indireta',
    serviceUnit: 'Box 01',
    procedurePerformed: 'Inlay cerâmico',
    professorId: 'prof-001',
    specialismId: 1,
    specialism: { id: 1, name: 'Dentística', description: 'Estética e restauração dental' },
    professor: prof1,
    evaluationCount: 2,
    status: 'scheduled',
  },
  {
    id: 8,
    title: 'Retratamento Endodôntico',
    date: '2026-05-19',
    academicSemester: '2026.1',
    goals: 'Avaliar técnica de retratamento de canal',
    serviceUnit: 'Box 03',
    procedurePerformed: 'Retratamento de canal',
    professorId: 'prof-002',
    specialismId: 3,
    specialism: { id: 3, name: 'Endodontia', description: 'Tratamento de canal' },
    professor: prof2,
    evaluationCount: 1,
    status: 'scheduled',
  },
  {
    id: 9,
    title: 'Ortodontia - Instalação de Aparelho',
    date: '2026-05-19',
    academicSemester: '2026.1',
    goals: 'Avaliar instalação de aparelho ortodôntico fixo',
    serviceUnit: 'Box 02',
    procedurePerformed: 'Colagem de brackets',
    professorId: 'prof-001',
    specialismId: 2,
    specialism: { id: 2, name: 'Ortodontia', description: 'Correção de má oclusão' },
    professor: prof1,
    evaluationCount: 0,
    status: 'scheduled',
  },
  {
    id: 10,
    title: 'Cirurgia Oral - Caso Complexo',
    date: '2026-05-22',
    academicSemester: '2026.1',
    goals: 'Avaliar exodontia de terceiro molar incluso',
    serviceUnit: 'Centro Cirúrgico',
    procedurePerformed: 'Exodontia de terceiro molar',
    professorId: 'prof-002',
    specialismId: 5,
    specialism: { id: 5, name: 'Cirurgia Oral', description: 'Procedimentos cirúrgicos' },
    professor: prof2,
    evaluationCount: 0,
    status: 'scheduled',
  },
  {
    id: 11,
    title: 'Avaliação Final - Periodontia',
    date: '2026-05-27',
    academicSemester: '2026.1',
    goals: 'Avaliação final do semestre em periodontia',
    serviceUnit: 'Box 04',
    procedurePerformed: 'Sondagem periodontal',
    professorId: 'prof-001',
    specialismId: 4,
    specialism: { id: 4, name: 'Periodontia', description: 'Tratamento gengival' },
    professor: prof1,
    evaluationCount: 0,
    status: 'scheduled',
  },
  {
    id: 12,
    title: 'Avaliação Final - Prótese',
    date: '2026-05-27',
    academicSemester: '2026.1',
    goals: 'Avaliação final do semestre em prótese dentária',
    serviceUnit: 'Laboratório de Prótese',
    procedurePerformed: 'Prótese parcial removível',
    professorId: 'prof-002',
    specialismId: 6,
    specialism: { id: 6, name: 'Prótese Dentária', description: 'Reabilitação oral' },
    professor: prof2,
    evaluationCount: 0,
    status: 'scheduled',
  },
];
