import type { Evaluation } from '../types';
import { MOCK_STUDENTS, MOCK_EXAMS } from './mockData';

// Extra evaluations for exam 1 (Dentística) — stu-001 and stu-004 already exist in MOCK_EVALUATIONS
export const MOCK_EXAM1_EXTRA_EVALUATIONS: Evaluation[] = [
  {
    id: 601,
    punctuality: 8.5,
    instrumental: 8.0,
    organizationOfServiceUnit: 8.5,
    biosecurity: 9.0,
    ethics: 8.5,
    concept: 8.5,
    observations: 'Bom domínio técnico. Precisa melhorar a velocidade de execução.',
    studentId: 'stu-002',
    examId: 1,
    student: MOCK_STUDENTS[1],
    exam: MOCK_EXAMS[0],
  },
  {
    id: 602,
    punctuality: 9.5,
    instrumental: 9.5,
    organizationOfServiceUnit: 9.0,
    biosecurity: 10.0,
    ethics: 9.5,
    concept: 9.5,
    observations: 'Excelente desempenho. Aluna referência na turma.',
    studentId: 'stu-003',
    examId: 1,
    student: MOCK_STUDENTS[2],
    exam: MOCK_EXAMS[0],
  },
  {
    id: 603,
    punctuality: 7.0,
    instrumental: 7.0,
    organizationOfServiceUnit: 7.0,
    biosecurity: 8.0,
    ethics: 7.5,
    concept: 7.0,
    observations: 'Desempenho satisfatório. Manter a evolução.',
    studentId: 'stu-005',
    examId: 1,
    student: MOCK_STUDENTS[4],
    exam: MOCK_EXAMS[0],
  },
  {
    id: 604,
    punctuality: 6.5,
    instrumental: 6.5,
    organizationOfServiceUnit: 6.0,
    biosecurity: 7.5,
    ethics: 7.0,
    concept: 6.5,
    observations: 'Aluno apresentou dificuldades na técnica. Necessita de supervisão adicional.',
    studentId: 'stu-006',
    examId: 1,
    student: MOCK_STUDENTS[5],
    exam: MOCK_EXAMS[0],
  },
  {
    id: 605,
    punctuality: 8.0,
    instrumental: 8.0,
    organizationOfServiceUnit: 7.5,
    biosecurity: 9.0,
    ethics: 8.0,
    concept: 8.0,
    observations: 'Bom desempenho geral. Técnica adequada.',
    studentId: 'stu-007',
    examId: 1,
    student: MOCK_STUDENTS[6],
    exam: MOCK_EXAMS[0],
  },
  {
    id: 606,
    punctuality: 5.5,
    instrumental: 5.5,
    organizationOfServiceUnit: 5.5,
    biosecurity: 6.5,
    ethics: 6.0,
    concept: 5.5,
    observations: 'Desempenho insuficiente. Recomendado reforço teórico e prática supervisionada.',
    studentId: 'stu-008',
    examId: 1,
    student: MOCK_STUDENTS[7],
    exam: MOCK_EXAMS[0],
  },
];

// Evaluations for exam 2 (Endodontia) — adds remaining students for semester comparison
export const MOCK_EXAM2_EXTRA_EVALUATIONS: Evaluation[] = [
  {
    id: 701,
    punctuality: 8.0,
    instrumental: 8.5,
    organizationOfServiceUnit: 7.5,
    biosecurity: 9.0,
    ethics: 8.0,
    concept: 8.2,
    observations: '',
    studentId: 'stu-001',
    examId: 2,
    student: MOCK_STUDENTS[0],
    exam: MOCK_EXAMS[1],
  },
  {
    id: 702,
    punctuality: 9.0,
    instrumental: 9.0,
    organizationOfServiceUnit: 8.5,
    biosecurity: 9.5,
    ethics: 9.0,
    concept: 9.0,
    observations: '',
    studentId: 'stu-003',
    examId: 2,
    student: MOCK_STUDENTS[2],
    exam: MOCK_EXAMS[1],
  },
  {
    id: 703,
    punctuality: 7.0,
    instrumental: 7.5,
    organizationOfServiceUnit: 7.0,
    biosecurity: 8.0,
    ethics: 7.5,
    concept: 7.3,
    observations: '',
    studentId: 'stu-006',
    examId: 2,
    student: MOCK_STUDENTS[5],
    exam: MOCK_EXAMS[1],
  },
];

// Evaluations for exam 3 (Ortodontia) — semester comparison
export const MOCK_EXAM3_EXTRA_EVALUATIONS: Evaluation[] = [
  {
    id: 801,
    punctuality: 7.5,
    instrumental: 8.0,
    organizationOfServiceUnit: 7.5,
    biosecurity: 8.5,
    ethics: 8.0,
    concept: 7.9,
    observations: '',
    studentId: 'stu-002',
    examId: 3,
    student: MOCK_STUDENTS[1],
    exam: MOCK_EXAMS[2],
  },
  {
    id: 802,
    punctuality: 8.5,
    instrumental: 8.5,
    organizationOfServiceUnit: 8.0,
    biosecurity: 9.5,
    ethics: 9.0,
    concept: 8.7,
    observations: '',
    studentId: 'stu-007',
    examId: 3,
    student: MOCK_STUDENTS[6],
    exam: MOCK_EXAMS[2],
  },
  {
    id: 803,
    punctuality: 7.0,
    instrumental: 7.0,
    organizationOfServiceUnit: 6.5,
    biosecurity: 8.0,
    ethics: 7.5,
    concept: 7.2,
    observations: '',
    studentId: 'stu-004',
    examId: 3,
    student: MOCK_STUDENTS[3],
    exam: MOCK_EXAMS[2],
  },
];
