import type { Evaluation, Specialism, User } from '../types';

export const MOCK_SPECIALISMS: Specialism[] = [
  { id: 1, name: 'Dentística', description: 'Estética e restauração dental' },
  { id: 2, name: 'Ortodontia', description: 'Correção de má oclusão' },
  { id: 3, name: 'Endodontia', description: 'Tratamento de canal' },
  { id: 4, name: 'Periodontia', description: 'Tratamento gengival' },
  { id: 5, name: 'Cirurgia Oral', description: 'Procedimentos cirúrgicos' },
  { id: 6, name: 'Prótese Dentária', description: 'Reabilitação oral' },
];

export const MOCK_STUDENTS: User[] = [
  {
    id: 'stu-001',
    name: 'Maria Souza',
    email: 'maria.souza@aluno.edu',
    roles: [{ id: 3, name: 'STUDENT' }],
  },
  {
    id: 'stu-002',
    name: 'João Pedro',
    email: 'joao.pedro@aluno.edu',
    roles: [{ id: 3, name: 'STUDENT' }],
  },
  {
    id: 'stu-003',
    name: 'Ana Clara da Silva',
    email: 'ana.clara@aluno.edu',
    roles: [{ id: 3, name: 'STUDENT' }],
  },
  {
    id: 'stu-004',
    name: 'Carlos Henrique',
    email: 'carlos.h@aluno.edu',
    roles: [{ id: 3, name: 'STUDENT' }],
  },
  {
    id: 'stu-005',
    name: 'Juliana Oliveira',
    email: 'juliana.o@aluno.edu',
    roles: [{ id: 3, name: 'STUDENT' }],
  },
  {
    id: 'stu-006',
    name: 'Marcos Vinicius',
    email: 'marcos.v@aluno.edu',
    roles: [{ id: 3, name: 'STUDENT' }],
  },
  {
    id: 'stu-007',
    name: 'Fernanda Lima',
    email: 'fernanda.l@aluno.edu',
    roles: [{ id: 3, name: 'STUDENT' }],
  },
  {
    id: 'stu-008',
    name: 'Rafael Costa',
    email: 'rafael.c@aluno.edu',
    roles: [{ id: 3, name: 'STUDENT' }],
  },
];

export const MOCK_PROFESSORS: User[] = [
  {
    id: 'prof-001',
    name: 'Dr. João Silva',
    email: 'joao.silva@odontaval.com',
    roles: [{ id: 2, name: 'PROFESSOR' }],
  },
  {
    id: 'prof-002',
    name: 'Dra. Mariana Costa',
    email: 'mariana.costa@odontaval.com',
    roles: [{ id: 2, name: 'PROFESSOR' }],
  },
];

export const MOCK_EVALUATIONS: Evaluation[] = [
  {
    id: 1,
    title: 'Avaliação clínica AV1',
    punctuality: -1.0,
    instrumental: -0.5,
    boxOrganization: -1.0,
    biosecurity: 0,
    ethics: -0.5,
    concept: -1.0,
    grade: 6.0,
    observations: 'Bom desempenho geral durante o atendimento.',
    evaluationNumber: 'AV1',
    date: '2026-05-07',
    academicSemester: '2026.1',
    goals: 'Avaliar restauração composta classe II',
    box: 'Box 01',
    procedurePerformed: 'Restauração composta',
    professorId: 'prof-001',
    studentId: 'stu-001',
    specialismId: 1,
  },
  {
    id: 2,
    title: 'Avaliação clínica AV1',
    punctuality: -2.0,
    instrumental: -1.0,
    boxOrganization: -2.0,
    biosecurity: -1.0,
    ethics: -1.5,
    concept: -2.0,
    grade: 0.5,
    observations: 'Precisa melhorar organização do box.',
    evaluationNumber: 'AV1',
    date: '2026-05-07',
    academicSemester: '2026.1',
    goals: 'Avaliar tratamento de canal',
    box: 'Box 03',
    procedurePerformed: 'Tratamento de canal',
    professorId: 'prof-002',
    studentId: 'stu-002',
    specialismId: 3,
  },
  {
    id: 3,
    title: 'Avaliação clínica AV1',
    punctuality: 0,
    instrumental: -0.5,
    boxOrganization: -0.5,
    biosecurity: 0,
    ethics: 0,
    concept: -0.5,
    grade: 8.5,
    observations: 'Excelente desempenho.',
    evaluationNumber: 'AV1',
    date: '2026-05-05',
    academicSemester: '2026.1',
    goals: 'Avaliação diagnóstica inicial',
    box: 'Box 02',
    procedurePerformed: 'Diagnóstico ortodôntico',
    professorId: 'prof-001',
    studentId: 'stu-003',
    specialismId: 2,
  },
];

export const MOCK_DASHBOARD_STATS = {
  totalStudents: 128,
  studentsThisMonth: 12,
  totalEvaluations: 342,
  evaluationsThisMonth: 18,
  pendingEvaluations: 5,
};
