import type { Evaluation, Exam } from '../types';
import { MOCK_SPECIALISMS, MOCK_PROFESSORS, MOCK_STUDENTS } from './mockData';

export const MOCK_EXTENDED_EXAMS: Exam[] = [
  {
    id: 10,
    title: 'Avaliação Clínica - Dentística I',
    date: '2025-01-20',
    academicSemester: '2025.1',
    goals: 'Restauração composta classe I',
    serviceUnit: 'Box 01',
    procedurePerformed: 'Restauração composta',
    professorId: 'prof-001',
    specialismId: 1,
    specialism: MOCK_SPECIALISMS[0],
    professor: MOCK_PROFESSORS[0],
  },
  {
    id: 11,
    title: 'Avaliação Clínica - Endodontia I',
    date: '2025-02-10',
    academicSemester: '2025.1',
    goals: 'Tratamento endodôntico unirradicular',
    serviceUnit: 'Box 03',
    procedurePerformed: 'Tratamento de canal',
    professorId: 'prof-002',
    specialismId: 3,
    specialism: MOCK_SPECIALISMS[2],
    professor: MOCK_PROFESSORS[1],
  },
  {
    id: 12,
    title: 'Avaliação Clínica - Dentística II',
    date: '2025-02-25',
    academicSemester: '2025.1',
    goals: 'Restauração composta classe II',
    serviceUnit: 'Box 02',
    procedurePerformed: 'Restauração composta',
    professorId: 'prof-001',
    specialismId: 1,
    specialism: MOCK_SPECIALISMS[0],
    professor: MOCK_PROFESSORS[0],
  },
  {
    id: 13,
    title: 'Avaliação Clínica - Periodontia',
    date: '2025-03-15',
    academicSemester: '2025.1',
    goals: 'Raspagem e alisamento radicular',
    serviceUnit: 'Box 04',
    procedurePerformed: 'Raspagem supragengival',
    professorId: 'prof-002',
    specialismId: 4,
    specialism: MOCK_SPECIALISMS[3],
    professor: MOCK_PROFESSORS[1],
  },
  {
    id: 14,
    title: 'Avaliação Clínica - Ortodontia',
    date: '2025-03-28',
    academicSemester: '2025.1',
    goals: 'Instalação de aparelho fixo',
    serviceUnit: 'Box 02',
    procedurePerformed: 'Braqueteamento',
    professorId: 'prof-001',
    specialismId: 2,
    specialism: MOCK_SPECIALISMS[1],
    professor: MOCK_PROFESSORS[0],
  },
  {
    id: 15,
    title: 'Avaliação Clínica - Endodontia II',
    date: '2025-04-10',
    academicSemester: '2025.1',
    goals: 'Tratamento endodôntico multirradicular',
    serviceUnit: 'Box 03',
    procedurePerformed: 'Tratamento de canal',
    professorId: 'prof-002',
    specialismId: 3,
    specialism: MOCK_SPECIALISMS[2],
    professor: MOCK_PROFESSORS[1],
  },
  {
    id: 16,
    title: 'Avaliação Clínica - Dentística III',
    date: '2025-04-22',
    academicSemester: '2025.1',
    goals: 'Restauração cerâmica indireta',
    serviceUnit: 'Box 01',
    procedurePerformed: 'Incrustação de cerâmica',
    professorId: 'prof-001',
    specialismId: 1,
    specialism: MOCK_SPECIALISMS[0],
    professor: MOCK_PROFESSORS[0],
  },
  {
    id: 17,
    title: 'Avaliação Clínica - Cirurgia Oral',
    date: '2025-05-05',
    academicSemester: '2025.1',
    goals: 'Exodontia de terceiro molar',
    serviceUnit: 'Box 05',
    procedurePerformed: 'Exodontia',
    professorId: 'prof-002',
    specialismId: 5,
    specialism: MOCK_SPECIALISMS[4],
    professor: MOCK_PROFESSORS[1],
  },
  // Exams for other students (class comparison)
  {
    id: 20,
    title: 'Avaliação Clínica - Periodontia',
    date: '2025-02-20',
    academicSemester: '2025.1',
    goals: 'Raspagem',
    serviceUnit: 'Box 04',
    procedurePerformed: 'Raspagem',
    professorId: 'prof-001',
    specialismId: 4,
    specialism: MOCK_SPECIALISMS[3],
    professor: MOCK_PROFESSORS[0],
  },
  {
    id: 21,
    title: 'Avaliação Clínica - Prótese',
    date: '2025-03-10',
    academicSemester: '2025.1',
    goals: 'Moldagem para prótese total',
    serviceUnit: 'Box 06',
    procedurePerformed: 'Moldagem',
    professorId: 'prof-002',
    specialismId: 6,
    specialism: MOCK_SPECIALISMS[5],
    professor: MOCK_PROFESSORS[1],
  },
];

// Extended evaluations for stu-001 (Maria Souza) — progression over 2025.1
export const MOCK_STU001_EVALUATIONS: Evaluation[] = [
  {
    id: 101,
    punctuality: 6.5,
    instrumental: 7.0,
    organizationOfServiceUnit: 6.5,
    biosecurity: 8.0,
    ethics: 7.5,
    concept: 7.0,
    observations: 'Início do semestre. Aluna ainda em adaptação aos procedimentos clínicos.',
    studentId: 'stu-001',
    examId: 10,
    student: MOCK_STUDENTS[0],
    exam: MOCK_EXTENDED_EXAMS[0],
  },
  {
    id: 102,
    punctuality: 7.0,
    instrumental: 7.5,
    organizationOfServiceUnit: 7.0,
    biosecurity: 8.5,
    ethics: 8.0,
    concept: 7.5,
    observations: 'Melhora perceptível no manejo do instrumental.',
    studentId: 'stu-001',
    examId: 11,
    student: MOCK_STUDENTS[0],
    exam: MOCK_EXTENDED_EXAMS[1],
  },
  {
    id: 103,
    punctuality: 7.5,
    instrumental: 7.5,
    organizationOfServiceUnit: 7.0,
    biosecurity: 9.0,
    ethics: 8.0,
    concept: 7.8,
    observations: 'Evolução consistente. Biossegurança sempre em destaque.',
    studentId: 'stu-001',
    examId: 12,
    student: MOCK_STUDENTS[0],
    exam: MOCK_EXTENDED_EXAMS[2],
  },
  {
    id: 104,
    punctuality: 7.5,
    instrumental: 8.0,
    organizationOfServiceUnit: 7.5,
    biosecurity: 9.0,
    ethics: 8.5,
    concept: 8.0,
    observations: 'Aluna demonstra boa postura profissional.',
    studentId: 'stu-001',
    examId: 13,
    student: MOCK_STUDENTS[0],
    exam: MOCK_EXTENDED_EXAMS[3],
  },
  {
    id: 105,
    punctuality: 8.0,
    instrumental: 8.0,
    organizationOfServiceUnit: 7.5,
    biosecurity: 9.5,
    ethics: 8.5,
    concept: 8.2,
    observations: 'Bom domínio técnico em ortodontia.',
    studentId: 'stu-001',
    examId: 14,
    student: MOCK_STUDENTS[0],
    exam: MOCK_EXTENDED_EXAMS[4],
  },
  {
    id: 106,
    punctuality: 8.5,
    instrumental: 8.5,
    organizationOfServiceUnit: 8.0,
    biosecurity: 9.5,
    ethics: 9.0,
    concept: 8.5,
    observations: 'Técnica endodôntica bem executada.',
    studentId: 'stu-001',
    examId: 15,
    student: MOCK_STUDENTS[0],
    exam: MOCK_EXTENDED_EXAMS[5],
  },
  {
    id: 107,
    punctuality: 8.5,
    instrumental: 9.0,
    organizationOfServiceUnit: 8.0,
    biosecurity: 10.0,
    ethics: 9.0,
    concept: 8.8,
    observations: 'Excelente evolução. Organização do box melhorou muito.',
    studentId: 'stu-001',
    examId: 16,
    student: MOCK_STUDENTS[0],
    exam: MOCK_EXTENDED_EXAMS[6],
  },
  {
    id: 108,
    punctuality: 9.0,
    instrumental: 9.0,
    organizationOfServiceUnit: 8.5,
    biosecurity: 10.0,
    ethics: 9.5,
    concept: 9.0,
    observations: 'Procedimento cirúrgico realizado com segurança e destreza.',
    studentId: 'stu-001',
    examId: 17,
    student: MOCK_STUDENTS[0],
    exam: MOCK_EXTENDED_EXAMS[7],
  },
];

// Evaluations for other students (class comparison data)
export const MOCK_CLASS_EVALUATIONS: Evaluation[] = [
  // stu-002 (João Pedro)
  {
    id: 201,
    punctuality: 7.5,
    instrumental: 8.0,
    organizationOfServiceUnit: 7.0,
    biosecurity: 8.5,
    ethics: 8.0,
    concept: 7.8,
    observations: '',
    studentId: 'stu-002',
    examId: 20,
    student: MOCK_STUDENTS[1],
    exam: MOCK_EXTENDED_EXAMS[8],
  },
  {
    id: 202,
    punctuality: 8.0,
    instrumental: 7.5,
    organizationOfServiceUnit: 8.0,
    biosecurity: 8.0,
    ethics: 8.5,
    concept: 8.0,
    observations: '',
    studentId: 'stu-002',
    examId: 21,
    student: MOCK_STUDENTS[1],
    exam: MOCK_EXTENDED_EXAMS[9],
  },
  // stu-006 (Marcos Vinicius)
  {
    id: 301,
    punctuality: 8.5,
    instrumental: 8.0,
    organizationOfServiceUnit: 7.5,
    biosecurity: 9.0,
    ethics: 8.5,
    concept: 8.3,
    observations: '',
    studentId: 'stu-006',
    examId: 10,
    student: MOCK_STUDENTS[5],
    exam: MOCK_EXTENDED_EXAMS[0],
  },
  // stu-007 (Fernanda Lima)
  {
    id: 401,
    punctuality: 9.0,
    instrumental: 8.5,
    organizationOfServiceUnit: 8.5,
    biosecurity: 9.5,
    ethics: 9.0,
    concept: 8.9,
    observations: '',
    studentId: 'stu-007',
    examId: 11,
    student: MOCK_STUDENTS[6],
    exam: MOCK_EXTENDED_EXAMS[1],
  },
  {
    id: 402,
    punctuality: 8.5,
    instrumental: 9.0,
    organizationOfServiceUnit: 8.0,
    biosecurity: 9.0,
    ethics: 9.5,
    concept: 8.8,
    observations: '',
    studentId: 'stu-007',
    examId: 20,
    student: MOCK_STUDENTS[6],
    exam: MOCK_EXTENDED_EXAMS[8],
  },
  // stu-008 (Rafael Costa)
  {
    id: 501,
    punctuality: 7.0,
    instrumental: 7.5,
    organizationOfServiceUnit: 7.5,
    biosecurity: 8.0,
    ethics: 7.5,
    concept: 7.5,
    observations: '',
    studentId: 'stu-008',
    examId: 12,
    student: MOCK_STUDENTS[7],
    exam: MOCK_EXTENDED_EXAMS[2],
  },
  {
    id: 502,
    punctuality: 7.5,
    instrumental: 8.0,
    organizationOfServiceUnit: 7.0,
    biosecurity: 8.5,
    ethics: 8.0,
    concept: 7.8,
    observations: '',
    studentId: 'stu-008',
    examId: 21,
    student: MOCK_STUDENTS[7],
    exam: MOCK_EXTENDED_EXAMS[9],
  },
];
