import type { Evaluation } from '../types';

// Extended evaluations for stu-001 (Maria Souza) — progression over 2026.1
export const MOCK_STU001_EVALUATIONS: Evaluation[] = [
  {
    id: 101,
    title: 'Avaliação clínica AV1',
    punctuality: -1.0,
    instrumental: -1.5,
    boxOrganization: -1.5,
    biosecurity: -0.5,
    ethics: -0.5,
    concept: -1.5,
    grade: 3.5,
    observations: 'Aluna ainda em adaptação aos procedimentos clínicos.',
    evaluationNumber: 'AV1',
    date: '2026-01-20',
    academicSemester: '2026.1',
    goals: 'Restauração composta classe I',
    box: 'Box 01',
    procedurePerformed: 'Restauração composta',
    professorId: 'prof-001',
    studentId: 'stu-001',
    specialismId: 1,
  },
  {
    id: 102,
    title: 'Avaliação clínica AV1',
    punctuality: -1.0,
    instrumental: -1.0,
    boxOrganization: -1.0,
    biosecurity: -0.5,
    ethics: -0.5,
    concept: -1.0,
    grade: 5.0,
    observations: 'Melhora perceptível no manejo do instrumental.',
    evaluationNumber: 'AV1',
    date: '2026-02-10',
    academicSemester: '2026.1',
    goals: 'Tratamento endodôntico unirradicular',
    box: 'Box 03',
    procedurePerformed: 'Tratamento de canal',
    professorId: 'prof-002',
    studentId: 'stu-001',
    specialismId: 3,
  },
  {
    id: 103,
    title: 'Avaliação clínica AV1',
    punctuality: -0.5,
    instrumental: -1.0,
    boxOrganization: -1.0,
    biosecurity: -0.5,
    ethics: -0.5,
    concept: -0.5,
    grade: 6.0,
    observations: 'Evolução consistente. Biossegurança sempre em destaque.',
    evaluationNumber: 'AV1',
    date: '2026-02-25',
    academicSemester: '2026.1',
    goals: 'Restauração composta classe II',
    box: 'Box 02',
    procedurePerformed: 'Restauração composta',
    professorId: 'prof-001',
    studentId: 'stu-001',
    specialismId: 1,
  },
  {
    id: 104,
    title: 'Avaliação clínica AV2',
    punctuality: -0.5,
    instrumental: -0.5,
    boxOrganization: -0.5,
    biosecurity: -0.5,
    ethics: -0.5,
    concept: -0.5,
    grade: 7.0,
    observations: 'Aluna demonstra boa postura profissional.',
    evaluationNumber: 'AV2',
    date: '2026-03-15',
    academicSemester: '2026.1',
    goals: 'Raspagem e alisamento radicular',
    box: 'Box 04',
    procedurePerformed: 'Raspagem supragengival',
    professorId: 'prof-002',
    studentId: 'stu-001',
    specialismId: 4,
  },
  {
    id: 105,
    title: 'Avaliação clínica AV2',
    punctuality: -0.5,
    instrumental: -0.5,
    boxOrganization: -0.5,
    biosecurity: 0,
    ethics: -0.5,
    concept: -0.5,
    grade: 8.0,
    observations: 'Bom domínio técnico em ortodontia.',
    evaluationNumber: 'AV2',
    date: '2026-03-28',
    academicSemester: '2026.1',
    goals: 'Instalação de aparelho fixo',
    box: 'Box 02',
    procedurePerformed: 'Braqueteamento',
    professorId: 'prof-001',
    studentId: 'stu-001',
    specialismId: 2,
  },
  {
    id: 106,
    title: 'Avaliação clínica AV2',
    punctuality: -0.5,
    instrumental: -0.5,
    boxOrganization: -0.5,
    biosecurity: 0,
    ethics: 0,
    concept: -0.5,
    grade: 8.5,
    observations: 'Técnica endodôntica bem executada.',
    evaluationNumber: 'AV2',
    date: '2026-04-10',
    academicSemester: '2026.1',
    goals: 'Tratamento endodôntico multirradicular',
    box: 'Box 03',
    procedurePerformed: 'Tratamento de canal',
    professorId: 'prof-002',
    studentId: 'stu-001',
    specialismId: 3,
  },
  {
    id: 107,
    title: 'Avaliação clínica AV3',
    punctuality: 0,
    instrumental: -0.5,
    boxOrganization: -0.5,
    biosecurity: 0,
    ethics: 0,
    concept: 0,
    grade: 9.0,
    observations: 'Excelente evolução. Organização do box melhorou muito.',
    evaluationNumber: 'AV3',
    date: '2026-04-22',
    academicSemester: '2026.1',
    goals: 'Restauração cerâmica indireta',
    box: 'Box 01',
    procedurePerformed: 'Incrustação de cerâmica',
    professorId: 'prof-001',
    studentId: 'stu-001',
    specialismId: 1,
  },
  {
    id: 108,
    title: 'Avaliação clínica AV3',
    punctuality: 0,
    instrumental: 0,
    boxOrganization: -0.5,
    biosecurity: 0,
    ethics: 0,
    concept: 0,
    grade: 9.5,
    observations: 'Procedimento cirúrgico realizado com segurança e destreza.',
    evaluationNumber: 'AV3',
    date: '2026-05-05',
    academicSemester: '2026.1',
    goals: 'Exodontia de terceiro molar',
    box: 'Box 05',
    procedurePerformed: 'Exodontia',
    professorId: 'prof-002',
    studentId: 'stu-001',
    specialismId: 5,
  },
];

// Evaluations for other students (class comparison data)
export const MOCK_CLASS_EVALUATIONS: Evaluation[] = [
  {
    id: 201,
    title: 'Avaliação clínica AV1',
    punctuality: -0.5,
    instrumental: -1.0,
    boxOrganization: -1.5,
    biosecurity: -0.5,
    ethics: -0.5,
    concept: -1.0,
    grade: 5.0,
    studentId: 'stu-002',
    evaluationNumber: 'AV1',
    date: '2026-02-20',
    academicSemester: '2026.1',
    goals: 'Raspagem',
    box: 'Box 04',
    procedurePerformed: 'Raspagem',
    professorId: 'prof-001',
    specialismId: 4,
  },
  {
    id: 202,
    title: 'Avaliação clínica AV2',
    punctuality: -0.5,
    instrumental: -1.0,
    boxOrganization: -1.0,
    biosecurity: -0.5,
    ethics: -0.5,
    concept: -0.5,
    grade: 6.0,
    studentId: 'stu-002',
    evaluationNumber: 'AV2',
    date: '2026-03-10',
    academicSemester: '2026.1',
    goals: 'Moldagem para prótese total',
    box: 'Box 06',
    procedurePerformed: 'Moldagem',
    professorId: 'prof-002',
    specialismId: 6,
  },
  {
    id: 301,
    title: 'Avaliação clínica AV1',
    punctuality: -0.5,
    instrumental: -1.0,
    boxOrganization: -1.0,
    biosecurity: -0.5,
    ethics: -0.5,
    concept: -0.5,
    grade: 6.0,
    studentId: 'stu-006',
    evaluationNumber: 'AV1',
    date: '2026-01-20',
    academicSemester: '2026.1',
    goals: 'Restauração composta classe I',
    box: 'Box 01',
    procedurePerformed: 'Restauração composta',
    professorId: 'prof-001',
    specialismId: 1,
  },
  {
    id: 401,
    title: 'Avaliação clínica AV1',
    punctuality: 0,
    instrumental: -0.5,
    boxOrganization: -0.5,
    biosecurity: 0,
    ethics: -0.5,
    concept: 0,
    grade: 8.5,
    studentId: 'stu-007',
    evaluationNumber: 'AV1',
    date: '2026-02-10',
    academicSemester: '2026.1',
    goals: 'Tratamento endodôntico unirradicular',
    box: 'Box 03',
    procedurePerformed: 'Tratamento de canal',
    professorId: 'prof-002',
    specialismId: 3,
  },
  {
    id: 402,
    title: 'Avaliação clínica AV2',
    punctuality: 0,
    instrumental: -0.5,
    boxOrganization: -0.5,
    biosecurity: 0,
    ethics: 0,
    concept: -0.5,
    grade: 8.5,
    studentId: 'stu-007',
    evaluationNumber: 'AV2',
    date: '2026-02-20',
    academicSemester: '2026.1',
    goals: 'Raspagem',
    box: 'Box 04',
    procedurePerformed: 'Raspagem',
    professorId: 'prof-001',
    specialismId: 4,
  },
  {
    id: 501,
    title: 'Avaliação clínica AV1',
    punctuality: -1.0,
    instrumental: -1.0,
    boxOrganization: -1.0,
    biosecurity: -0.5,
    ethics: -0.5,
    concept: -1.0,
    grade: 5.0,
    studentId: 'stu-008',
    evaluationNumber: 'AV1',
    date: '2026-02-25',
    academicSemester: '2026.1',
    goals: 'Restauração composta classe II',
    box: 'Box 02',
    procedurePerformed: 'Restauração composta',
    professorId: 'prof-001',
    specialismId: 1,
  },
  {
    id: 502,
    title: 'Avaliação clínica AV2',
    punctuality: -0.5,
    instrumental: -0.5,
    boxOrganization: -1.0,
    biosecurity: -0.5,
    ethics: -0.5,
    concept: -0.5,
    grade: 6.5,
    studentId: 'stu-008',
    evaluationNumber: 'AV2',
    date: '2026-03-10',
    academicSemester: '2026.1',
    goals: 'Moldagem para prótese total',
    box: 'Box 06',
    procedurePerformed: 'Moldagem',
    professorId: 'prof-002',
    specialismId: 6,
  },
];
